=== xabilazkano/FinalChallenge/XML SQL JavaDoc/XML/concesionario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="vehiculos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="coches" >
          <xs:complexType>
            <xs:sequence>
              <xs:element name="coche" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element type="xs:integer" name="id_serie"/>
                  <xs:element name="matricula">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:minLength value="7"/>
                        <xs:maxLength value="7"/>
                        <xs:pattern value="[A-Z0-9]+"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:element>
                  <xs:element name="numero_bastidor">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:maxLength value="17"/>
                        <xs:minLength value="17"/>
                       <xs:pattern value="[A-Z0-9]+"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:element>
                  <xs:element type="xs:string" name="color"/>
                  <xs:element type="xs:integer" name="numero_asientos"/>
                  <xs:element type="xs:integer" name="precio"/>
                  <xs:element type="xs:string" name="marca"/>
                  <xs:element type="xs:string" name="modelo"/>
                  <xs:element type="xs:date" name="fecha_fabricacion"/>
                  <xs:element type="xs:integer" name="numero_puertas"/>
                  <xs:element type="xs:integer" name="capacidad_maletero"/>
                </xs:sequence>
              </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          </xs:element>
           <xs:element name="camiones" >
          <xs:complexType>
            <xs:sequence>
              <xs:element name="camion" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element type="xs:integer" name="id_serie"/>
                  <xs:element name="matricula">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                         <xs:minLength value="7"/>
                        <xs:maxLength value="7"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:element>
                  <xs:element name="numero_bastidor">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:maxLength value="17"/>
                        <xs:minLength value="17"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:element>
                  <xs:element type="xs:string" name="color"/>
                  <xs:element type="xs:integer" name="numero_asientos"/>
                  <xs:element type="xs:integer" name="precio"/>
                  <xs:element type="xs:string" name="marca"/>
                  <xs:element type="xs:string" name="modelo"/>
                  <xs:element type="xs:date" name="fecha_fabricacion"/>
                  <xs:element type="xs:integer" name="carga"/>
                  <xs:element name="tipo_mercancia">
                   <xs:simpleType >
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="G"/>
                      <xs:enumeration value="A"/>
                      <xs:enumeration value="P"/>
                    </xs:restriction>
                  </xs:simpleType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== xabilazkano/FinalChallenge/XML SQL JavaDoc/XML/concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="concesionario.xsl" type="text/xsl"?>
<vehiculos  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="concesionario.xsd">
<coches>
<coche>
<id_serie>1</id_serie>
<matricula>5432LKJ</matricula>
<numero_bastidor>1A8S7F6G7F9D9G8F8</numero_bastidor>
<color>Azul</color>
<numero_asientos>5</numero_asientos>
<precio>20000</precio>
<marca>Ford</marca>
<modelo>Mondeo</modelo>
<fecha_fabricacion>2011-04-22</fecha_fabricacion>
<numero_puertas>5</numero_puertas>
<capacidad_maletero>10</capacidad_maletero>
</coche>
<coche>
<id_serie>2</id_serie>
<matricula>5232LKJ</matricula>
<numero_bastidor>4D3J4F6G7F9D9G8F8</numero_bastidor>
<color>Negro</color>
<numero_asientos>5</numero_asientos>
<precio>23200</precio>
<marca>Ford</marca>
<modelo>Fiesta</modelo>
<fecha_fabricacion>2011-04-22</fecha_fabricacion>
<numero_puertas>5</numero_puertas>
<capacidad_maletero>10</capacidad_maletero>
</coche>
</coches>
<camiones>
<camion>
<id_serie>3</id_serie>
<matricula>8566HKJ</matricula>
<numero_bastidor>1A8S7F6G7F9D2J4NM</numero_bastidor>
<color>Blanco</color>
<numero_asientos>2</numero_asientos>
<precio>23200</precio>
<marca>Renault</marca>
<modelo>Magnum</modelo>
<fecha_fabricacion>2002-04-22</fecha_fabricacion>
<carga>5</carga>
<tipo_mercancia>G</tipo_mercancia>
</camion>
<camion>
<id_serie>3</id_serie>
<matricula>8126HKJ</matricula>
<numero_bastidor>1A8S7F6G7F7H6J4NM</numero_bastidor>
<color>Rojo</color>
<numero_asientos>2</numero_asientos>
<precio>25000</precio>
<marca>Renault</marca>
<modelo>Magnum</modelo>
<fecha_fabricacion>2002-04-22</fecha_fabricacion>
<carga>5</carga>
<tipo_mercancia>A</tipo_mercancia>
</camion>
</camiones>
</vehiculos>
